Add PR template
Otus-DevOps-2018-02/mleonovvv_infra pull request #1
Opened 2018-03-05 15:34 UTC by mleonovvv

Добавил шаблон для Pull Request'ов

2018-03-13 08:47 UTC, vitkhab requested changes
Оформи, пожалуйста, PR по шаблону.
И создай такой же PR ко второму своему репозиторию https://github.com/Otus-DevOps-2018-02/mleonovvv_microservices

2018-03-21 14:31 UTC, serjs commented
@mleonovvv Привет!  Тебе нужна помощь с выполнением ДЗ по запросу Виталия?

2018-03-22 17:42 UTC, mleonovvv commented
@serjs Привет! нет, задание понятно, просто проблемы со временем для него)

2018-03-22 17:44 UTC, mleonovvv commented
Нужно переделать задание на другом компьютере, поэтому пересоздам PR

2018-03-22 17:44 UTC, closed without merging