Ansible 2
Otus-DevOps-2018-02/mleonovvv_infra pull request #11
Opened 2018-05-01 17:28 UTC by mleonovvv

# Выполнено ДЗ № 10

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Создан общий playbook и один сценарий
 - Создан общий playbook и много сценариев
 - Создано много playbook'ов
 - Созданы playbook'и для провижинга
 - Изменен провижининг для packer на ansible

## Как запустить проект:
 -  запустить `ansible-playbook site.yml` из каталога ansible

## Как проверить работоспособность:
 - Например, перейти по ссылке http://app:9292

## PR checklisk
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-05-08 14:47 UTC, Nklya requested changes
Ревью этого ДЗ будет после фикса конфликтов и мержа все принятых PR.

2018-05-10 16:21 UTC, mleonovvv commented
Пофиксил

2018-05-14 08:30 UTC, Nklya approved these changes
Добрый день.

Михаил, условия ДЗ выполнены, все выглядит ок 👍

2018-05-14 08:30 UTC, Nklya commented on terraform/modules/db/main.tf
> +  #  provisioner "file" {
В модуле `app` тоже нужно было выключить провижининг.

2018-05-14 08:31 UTC, merged

2018-05-14 08:31 UTC, Nklya commented
Смержено для проверки следующего.